app:
    resource: "@AppBundle/Controller/"
    type:     annotation

homepage:
    path: /
    defaults:
        _controller: AppBundle:Main:homepage

easy_admin:
    resource: "@AppBundle/Controller/EasyAdmin/AppAdminController.php"
    type: annotation
    prefix: /eadmin